image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - test

test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml run django_gunicorn python manage.py test


