# Generated by Django 4.1.6 on 2023-02-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='description',
            new_name='recipe',
        ),
        migrations.AddField(
            model_name='food',
            name='youtuve_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
