# Generated by Django 4.1.6 on 2023-02-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_description_food_recipe_food_youtuve_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='youtuve_link',
            new_name='youtube_link',
        ),
    ]
