# Generated by Django 4.1.6 on 2023-02-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_youtuve_link_food_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='main_ingredients',
        ),
        migrations.AddField(
            model_name='food',
            name='main_ingredients',
            field=models.ManyToManyField(to='main_app.ingredient'),
        ),
    ]
